server:
  user_address: ":3000"
  user_address_http: "go-superindo-ecommerce-production.up.railway.app"

database:
  host: containers-us-west-123.railway.app
  port: 7261
  user: postgres
  password: TsLpJjIOnNeKAe7e0ebB
  dbname: railway