server:
  user_address: ":8080"
  user_address_http: "localhost:8080"

database:
  host: containers-us-west-123.railway.app
  port: 7261
  user: postgres
  password: TsLpJjIOnNeKAe7e0ebB
  dbname: railway